/**
 * One-off helper: download the Manrope woff2 files (latin + latin-ext subsets,
 * weights 400/500/600/700/800) from Google Fonts and emit a self-hosted
 * @font-face stylesheet. Run with: bun scripts/fetch-manrope.ts
 * The generated fonts are served same-origin from /assets/fonts so the app's
 * strict CSP (font-src 'self') permits them without an external CDN.
 */
import { writeFile, mkdir } from "node:fs/promises";

const cssRes = await fetch(
	"https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap",
	{
		headers: {
			"User-Agent":
				"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36",
		},
	},
);
if (!cssRes.ok) throw new Error(`Google Fonts CSS -> ${cssRes.status}`);
const css = await cssRes.text();
const outDir = "src/client/fonts";
await mkdir(outDir, { recursive: true });

const blocks = css.split("@font-face").slice(1);
// Keep only latin (U+0000-00FF) and latin-ext (U+0100-02BA) subsets.
const wanted = [
	{ key: "U+0000-00FF", suffix: "" },
	{ key: "U+0100-02BA", suffix: "-ext" },
];

const faces: string[] = [];

for (const block of blocks) {
	const weightM = block.match(/font-weight:\s*(\d+)/);
	const rangeM = block.match(/unicode-range:\s*([^;]+);/);
	const urlM = block.match(
		/url\((https:\/\/[^)]+\.woff2)\)\s+format\('woff2'\)/,
	);
	if (!weightM || !rangeM || !urlM) continue;
	const weight = weightM[1]!;
	const range = rangeM[1]!.trim();
	const url = urlM[1]!;
	const subset = wanted.find((w) => range.includes(w.key));
	if (!subset) continue;

	const filename = `Manrope-${weight}${subset.suffix}.woff2`;
	const buf = await fetch(url).then((r) => {
		if (!r.ok) throw new Error(`fetch ${url} -> ${r.status}`);
		return r.arrayBuffer();
	});
	await writeFile(`${outDir}/${filename}`, Buffer.from(buf));

	faces.push(
		`@font-face {
  font-family: "Manrope";
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url("/assets/fonts/${filename}") format("woff2");
  unicode-range: ${range};
}`,
	);
}

const fontsCss = `/* Self-hosted Manrope (latin + latin-ext, weights 400-800).
   Served same-origin from /assets/fonts so the app's strict CSP
   (font-src 'self') allows it. Generated by scripts/fetch-manrope.ts. */
${faces.join("\n\n")}
`;
await writeFile(`${outDir}/fonts.css`, fontsCss);
console.log(
	`Wrote ${faces.length} @font-face blocks and woff2 files to ${outDir}`,
);
